spring.application.name=rider-service
# These variables will be filled by your Docker Compose file later
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# This tells Hibernate to create tables automatically for your Java classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka Broker
spring.kafka.bootstrap-servers=kafka:29092

# Deserialization: How to turn bytes back into Java Objects
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Consumer Group: Multiple instances of Driver-Service will share the load
spring.kafka.consumer.group-id=driver-availability-group
spring.kafka.consumer.auto-offset-reset=earliest

# Security: Only allow deserialization of our specific event package
spring.kafka.consumer.properties.spring.json.trusted.packages=com.kiran.ridersharing.event