spring.application.name=driver-service
# If not default 8080 port will be selected
# server.port=8081 -> Added alternative in Docker-compose.yml in environment section

# These variables will be filled by your Docker Compose file later
# Redis configuration
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}

# To allow the CRUD(Blocking way) & Reactive(Non-Blocking way) in DriverLocationController
# we need to set the application type to be in Servlet(Tomcat), to avoid Spring-boot's confusion about the "Web-type".
spring.main.web-application-type=servlet

# Kafka Broker
spring.kafka.bootstrap-servers=kafka:29092

# Deserialization: How to turn bytes back into Java Objects
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# THE DELEGATES (Check these carefully for typos)
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer

# Consumer Group: Multiple instances of Driver-Service will share the load
spring.kafka.consumer.group-id=driver-availability-group
spring.kafka.consumer.auto-offset-reset=earliest

# Security: Only allow deserialization of our specific event package
spring.kafka.consumer.properties.spring.json.trusted.packages=com.kiran.ridersharing.event,com.kiran.driversharing.event

# Map the remote class name to your local class name
spring.kafka.consumer.properties.spring.json.type.mapping=com.kiran.ridersharing.event.TripEvent:com.kiran.driversharing.event.TripEvent

# PRODUCER: To send TripEventCompensation back to Rider-Service
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=true