spring.application.name=driver-service
# If not default 8080 port will be selected
# server.port=8081 -> Added alternative in Docker-compose.yml in environment section

# These variables will be filled by your Docker Compose file later
# Redis configuration
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}

# To allow the CRUD(Blocking way) & Reactive(Non-Blocking way) in DriverLocationController
# we need to set the application type to be in Servlet(Tomcat), to avoid Spring-boot's confusion about the "Web-type".
spring.main.web-application-type=servlet